version: "3"

services:
  gost:
    image: ginuerzh/gost
    restart: always
    command: -C /gost/config.json
    network_mode: "host"
    volumes:
      - ./gost:/gost
  smartdns:
    image: ghostry/smartdns
    restart: always
    network_mode: "host"
    volumes:
      - ./smartdns:/smartdns